<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule </name>
  <uuid>40bdb8bf-f72b-4fff-832e-b4840e072677</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then
	set decision to "Hello " + Name + "! " + 'Weather advice';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
